### ISSUE TITLE
New version Oct 2024 and still issue at connection (Vertuo_DV6)

### ISSUE THREAD

**Issue by nxor** [bulldog5046/ha_nespresso_ingetration#21] opened 2024-11-03 02:39 UTC
I added some logs along the code, but I cannot get it to successfully do the read_gatt_char...

2024-11-02 21:44:18.323 DEBUG (MainThread) [custom_components.nespresso.nespresso] Nespresso is connected: True
2024-11-02 21:44:18.323 DEBUG (MainThread) [custom_components.nespresso.nespresso] Nespresso auth_key: f31xxxxx4074c4b
2024-11-02 21:44:18.952 ERROR (MainThread) [custom_components.nespresso.nespresso] Failed to connect to Nespresso device: Vertuo_DV6_XXXXXXX
2024-11-02 21:44:18.953 ERROR (MainThread) [custom_components.nespresso.nespresso] Can't init model: 'NoneType' object has no attribute 'read_gatt_char'

it fails here:
nespresso.py line 118
        try:
            # Test reading protected property to verify auth
            state = await client.read_gatt_char(CHAR_UUID_STATE, response=True)
        except Exception as e:
            _LOGGER.error(f'Failed to connect to Nespresso device: {device.name}')
            return False

Any idea ?

**Comment by bulldog5046** [comment] 2024-11-03 10:29
Duplicate of #12

**Closed as completed by bulldog5046** 2024-11-03 10:29 UTC
